-- check for duplicate values in primary key column
select 
	cst_id, 
	count(*)
from bronze.crm_cust_info
group by cst_id
having count(*) > 1

-- checking for leading and trailing spaces in string columns
select cst_key
from bronze.crm_cust_info
where cst_key != TRIM(cst_key)

select cst_firstname
from bronze.crm_cust_info
where cst_firstname != TRIM(cst_firstname)

select cst_lastname
from bronze.crm_cust_info
where cst_lastname != TRIM(cst_lastname)

-- selecting distinct values in marital status and gender

select distinct cst_marital_status
from bronze.crm_cust_info

select distinct cst_gndr
from bronze.crm_cust_info

-- checking for leading and trailing spaces in prd_key column
select prd_key
from bronze.crm_prd_info
where prd_line != trim(prd_key)

-- matching the category id for the tables crm_prd_info and erp_px_cat_g1v2
select replace(substring(prd_key, 1, 5), '-', '_')
from bronze.crm_prd_info

select id from bronze.erp_px_cat_g1v2

-- selecting distinct values in prd_line column
select distinct prd_line
from bronze.crm_prd_info

-- identifying rows where prd_start_dt is greater than prd_end_dt (which is impossible)
-- Observation: end dates can be generated by the next start date - 1
select *
from bronze.crm_prd_info
where prd_start_dt > prd_end_dt